### ISSUE TITLE
your code won't work on visual studio 

### ISSUE THREAD

**Issue by Jerem584** [omaflak/Asynchronous-Socket-Class-C-Windows#4]
https://github.com/OmarAflak/Asynchronous-Socket-Class-C-Windows/blob/master/src/SocketClient.cpp#L110

you can't do this on visual studio compiler

to fix it -> 
        char* buff;
        buff = new char[p];
        for (int i = 0; i < p; i++) {
            buff[i] = 0;  
        }

**Comment by omaraflak** [comment]
Hi.

Don't know what you're doing, but I really wouldn't advise using that code for anything serious. I did it back at the time for educating myself. You can look at socket.io or boost.

That said, it's weird that `char buff[p]` isn't supported in visual studio compiler (never used it) ... try setting `-std=c++11` flag for the compiler (probably somewhere in the settings of AS).

**Comment by Jerem584** [comment]
array must have a constant value, on gcc you can compile it, on vs u can't, just telling you, and yeha this code is ...
